# Generated by Django 3.2.8 on 2021-10-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_title_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='title',
            new_name='topic',
        ),
    ]
